/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as HoudunrenImport } from './pages/houdunren'
import { Route as AboutImport } from './pages/about'
import { Route as IndexImport } from './pages/index'
import { Route as FrontTopicImport } from './pages/front/topic'

// Create/Update Routes

const HoudunrenRoute = HoudunrenImport.update({
  id: '/houdunren',
  path: '/houdunren',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const FrontTopicRoute = FrontTopicImport.update({
  id: '/front/topic',
  path: '/front/topic',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/houdunren': {
      id: '/houdunren'
      path: '/houdunren'
      fullPath: '/houdunren'
      preLoaderRoute: typeof HoudunrenImport
      parentRoute: typeof rootRoute
    }
    '/front/topic': {
      id: '/front/topic'
      path: '/front/topic'
      fullPath: '/front/topic'
      preLoaderRoute: typeof FrontTopicImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/houdunren': typeof HoudunrenRoute
  '/front/topic': typeof FrontTopicRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/houdunren': typeof HoudunrenRoute
  '/front/topic': typeof FrontTopicRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/houdunren': typeof HoudunrenRoute
  '/front/topic': typeof FrontTopicRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/houdunren' | '/front/topic'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/houdunren' | '/front/topic'
  id: '__root__' | '/' | '/about' | '/houdunren' | '/front/topic'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HoudunrenRoute: typeof HoudunrenRoute
  FrontTopicRoute: typeof FrontTopicRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HoudunrenRoute: HoudunrenRoute,
  FrontTopicRoute: FrontTopicRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/houdunren",
        "/front/topic"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/houdunren": {
      "filePath": "houdunren.tsx"
    },
    "/front/topic": {
      "filePath": "front/topic.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
