/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'

// Create Virtual Routes

const FrontRouteLazyImport = createFileRoute('/_front')()
const FrontIndexLazyImport = createFileRoute('/_front/')()
const FrontSystemLazyImport = createFileRoute('/_front/system')()
const FrontProjectLazyImport = createFileRoute('/_front/project')()

// Create/Update Routes

const FrontRouteLazyRoute = FrontRouteLazyImport.update({
  id: '/_front',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/_front/route.lazy').then((d) => d.Route))

const FrontIndexLazyRoute = FrontIndexLazyImport.update({
  path: '/',
  getParentRoute: () => FrontRouteLazyRoute,
} as any).lazy(() => import('./pages/_front/index.lazy').then((d) => d.Route))

const FrontSystemLazyRoute = FrontSystemLazyImport.update({
  path: '/system',
  getParentRoute: () => FrontRouteLazyRoute,
} as any).lazy(() => import('./pages/_front/system.lazy').then((d) => d.Route))

const FrontProjectLazyRoute = FrontProjectLazyImport.update({
  path: '/project',
  getParentRoute: () => FrontRouteLazyRoute,
} as any).lazy(() => import('./pages/_front/project.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_front': {
      id: '/_front'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof FrontRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/_front/project': {
      id: '/_front/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof FrontProjectLazyImport
      parentRoute: typeof FrontRouteLazyImport
    }
    '/_front/system': {
      id: '/_front/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof FrontSystemLazyImport
      parentRoute: typeof FrontRouteLazyImport
    }
    '/_front/': {
      id: '/_front/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof FrontIndexLazyImport
      parentRoute: typeof FrontRouteLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  FrontRouteLazyRoute: FrontRouteLazyRoute.addChildren({
    FrontProjectLazyRoute,
    FrontSystemLazyRoute,
    FrontIndexLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_front"
      ]
    },
    "/_front": {
      "filePath": "_front/route.lazy.tsx",
      "children": [
        "/_front/project",
        "/_front/system",
        "/_front/"
      ]
    },
    "/_front/project": {
      "filePath": "_front/project.lazy.tsx",
      "parent": "/_front"
    },
    "/_front/system": {
      "filePath": "_front/system.lazy.tsx",
      "parent": "/_front"
    },
    "/_front/": {
      "filePath": "_front/index.lazy.tsx",
      "parent": "/_front"
    }
  }
}
ROUTE_MANIFEST_END */
