/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as FrontRouteImport } from './pages/front/route'
import { Route as FrontSystemImport } from './pages/front/system'
import { Route as FrontProjectImport } from './pages/front/project'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const FrontAboutLazyImport = createFileRoute('/front/about')()

// Create/Update Routes

const FrontRouteRoute = FrontRouteImport.update({
  path: '/front',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./pages/index.lazy').then((d) => d.Route))

const FrontAboutLazyRoute = FrontAboutLazyImport.update({
  path: '/about',
  getParentRoute: () => FrontRouteRoute,
} as any).lazy(() => import('./pages/front/about.lazy').then((d) => d.Route))

const FrontSystemRoute = FrontSystemImport.update({
  path: '/system',
  getParentRoute: () => FrontRouteRoute,
} as any)

const FrontProjectRoute = FrontProjectImport.update({
  path: '/project',
  getParentRoute: () => FrontRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/front': {
      id: '/front'
      path: '/front'
      fullPath: '/front'
      preLoaderRoute: typeof FrontRouteImport
      parentRoute: typeof rootRoute
    }
    '/front/project': {
      id: '/front/project'
      path: '/project'
      fullPath: '/front/project'
      preLoaderRoute: typeof FrontProjectImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/system': {
      id: '/front/system'
      path: '/system'
      fullPath: '/front/system'
      preLoaderRoute: typeof FrontSystemImport
      parentRoute: typeof FrontRouteImport
    }
    '/front/about': {
      id: '/front/about'
      path: '/about'
      fullPath: '/front/about'
      preLoaderRoute: typeof FrontAboutLazyImport
      parentRoute: typeof FrontRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  FrontRouteRoute: FrontRouteRoute.addChildren({
    FrontProjectRoute,
    FrontSystemRoute,
    FrontAboutLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/front"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/front": {
      "filePath": "front/route.tsx",
      "children": [
        "/front/project",
        "/front/system",
        "/front/about"
      ]
    },
    "/front/project": {
      "filePath": "front/project.tsx",
      "parent": "/front"
    },
    "/front/system": {
      "filePath": "front/system.tsx",
      "parent": "/front"
    },
    "/front/about": {
      "filePath": "front/about.lazy.tsx",
      "parent": "/front"
    }
  }
}
ROUTE_MANIFEST_END */
